version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php


  php:
    container_name: php
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - './src:/var/www/html'